# Generated by Django 5.1.4 on 2024-12-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='watch_for',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('unisex', 'Unisex')], default='unisex', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='watch_type',
            field=models.CharField(choices=[('analog', 'Analog'), ('digital', 'Digital'), ('smart', 'Smart')], max_length=50),
        ),
    ]
