# Generated by Django 5.1.4 on 2024-12-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_image_alter_product_watch_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='watch_for',
            field=models.CharField(choices=[('Men ', 'Men Watch'), ('Women ', 'Women Watch'), ('Kids ', 'Kids Watch'), ('Unisex ', 'Unisex Watch')], default='unisex', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='watch_type',
            field=models.CharField(choices=[('Analog ', 'Analog Watch'), ('Digital ', 'Digital Watch'), ('Smart ', 'Smart Watch')], max_length=50),
        ),
    ]
