# Generated by Django 5.1.4 on 2024-12-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_product_watch_for_alter_product_watch_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='watch_for',
            field=models.CharField(choices=[('Men Watch', 'Men Watch'), ('Women Watch', 'Women Watch'), ('Kids Watch', 'Kids Watch'), ('Unisex Watch', 'Unisex Watch')], default='unisex', max_length=50),
        ),
    ]
