# Generated by Django 5.1.4 on 2024-12-25 14:55

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_featured_collections'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('watch_description', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.models.featured_collections_path)),
            ],
        ),
        migrations.DeleteModel(
            name='Featured_Collections',
        ),
    ]
