# Generated by Django 5.1.4 on 2024-12-28 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_featuredcollections_delete_featured_collections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='watch_for',
            field=models.CharField(choices=[('Men Watch', 'Men Watch'), ('Women Watch', 'Women Watch'), ('Kids Watch', 'Kids Watch'), ('Unisex Watch', 'Unisex Watch')], default='Unisex Watch', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='watch_type',
            field=models.CharField(choices=[('Analog', 'Analog Watch'), ('Digital', 'Digital Watch'), ('Smart', 'Smart Watch')], default='Analog', max_length=50),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
